# Generated by Django 6.0 on 2025-12-23 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Incident', 'Incident'), ('Vendor Issue', 'Vendor Issue'), ('QA Issue', 'QA Issue'), ('Electrical', 'Electrical'), ('Mechanical', 'Mechanical'), ('Environmental', 'Environmental'), ('Uncategorized', 'Uncategorized')], max_length=50)),
                ('tags', models.JSONField(default=list)),
                ('severity', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed', to='core.rawinput')),
            ],
        ),
    ]
